Added firstDay option to datepicker control
wintercms/wn-builder-plugin pull request #4
Opened 2021-05-09 12:50 UTC by arvislacis

Added `firstDay` (first day of the week) option to datepicker control for Builder plugin. `firstDay` option itself was introduced in https://github.com/octobercms/october/pull/2940

2021-05-10 02:18 UTC, bennothommo requested changes

2021-05-10 02:18 UTC, bennothommo commented on classes/StandardControlsRegistry.php
> +                'default' => 'datetime',
@arvislacis This needs to default to Sunday (`"0"`).

```suggestion
                'default' => '0',
```

2021-05-10 02:18 UTC, bennothommo commented on classes/StandardControlsRegistry.php
> +                'ignoreIfEmpty' => true,
@arvislacis Can you double-check that setting it to Sunday works? I might be mistaken, but a string `"0"` is still considered empty and might be stripped from the widget config.

2021-05-10 02:18 UTC, bennothommo commented on classes/StandardControlsRegistry.php
> +                'sortOrder' => 86
```suggestion
                'sortOrder' => 86,
```

2021-05-10 02:18 UTC, bennothommo commented on classes/StandardControlsRegistry.php
> +                    '6' => Lang::get('winter.builder::lang.form.property_datepicker_first_day_saturday')
```suggestion
                    '6' => Lang::get('winter.builder::lang.form.property_datepicker_first_day_saturday'),
```

2021-05-10 08:05 UTC, arvislacis commented on classes/StandardControlsRegistry.php
> +                'ignoreIfEmpty' => true,
@bennothommo I double-checked and "0" is not considered empty - if you set or leave it to Sunday (default) then the value `0` is written into `fields.yaml` file.

So I added another commit https://github.com/wintercms/wn-builder-plugin/pull/4/commits/04c0094ad640cf3f26dc1d631de5493e25bd0a80 which adds default option with empty string `""`.

Also sorry for `default' => 'datetime',` - I was looking to another option as an example and accidentally took default value from it.

2021-05-10 08:27 UTC, arvislacis commented on classes/StandardControlsRegistry.php
> +                'ignoreIfEmpty' => true,
In my opinion it's better to don't force Sunday and "0" value for all users as default option, especially if it's written into `fields.yaml` as I mentioned... Although it's very unlikely there also may be situation in the future where the system's default the first day of the week value will be changed or some global, per user configuration will be invented. So empty string `''` would be better choice here.

2021-05-10 15:26 UTC, arvislacis commented
@bennothommo Anything else needed from my side?

2021-05-11 04:07 UTC, bennothommo commented
@arvislacis Nope, just needs to be tested.

2021-05-14 06:59 UTC, arvislacis commented
@bennothommo Maybe I can help with testing somehow or (so this can be merged and closed)? Overall I don't see any major points where and how this pull request could break things or don't work, especially after the last commit which sets default value to empty string (so no default/existing configurations are changed either). For one of my personal projects this worked without any issues. :)

2021-05-14 08:38 UTC, bennothommo commented
@arvislacis Looks good to me. Merging.

2021-05-14 08:39 UTC, merged